amcl:
  ros__parameters:
    use_sim_time: True

    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    global_frame_id: "map"
    scan_topic: scan

    alpha1: 0.01 # rotational noise while rotating
    alpha2: 0.001 # rotational noise while translating
    alpha3: 0.01 # translational noise while translating
    alpha4: 0.002 # translational noise while rotating
    alpha5: 0.01 # translational related noise param. only used for odom_model_type=omni
    
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 10.0
    laser_min_range: 0.05
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 5000
    min_particles: 300
    pf_err: 0.05 # kld_err, why does it have a new name?
    pf_z: 0.99 # kld_z
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 0.1
    update_min_a: 0.1
    update_min_d: 0.3
    z_hit: 0.5 # laser_z_hit
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    
    selective_resampling: true # old. removed?

map_server:
  ros__parameters:
    use_sim_time: True
    # Overridden in launch by the "map" launch configuration or provided default value.
    # To use in yaml, remove the default "map" value in the tb3_simulation_launch.py file & provide full path to map below.
    yaml_filename: ""