slam_gmapping:
  ros__parameters:
    base_frame: "base_footprint"
    odom_frame: "odom"      
    map_frame:  "map"     
    map_update_interval:  5.0 
    
    # Default: autodetect. Set maxUrange and maxRange for manual settings
    # maxUrange:          10.0
    # maxRange:           10.0
    minimumScore:         0
    
    sigma:                0.05
    kernelSize:           1 
    lstep:                0.05
    astep:                0.05
    iterations:           5 
    lsigma:               0.075
    ogain:                3.0
    lskip:                0

    srr:                  0.1
    srt:                  0.2
    str:                  0.1
    stt:                  0.2

    linearUpdate:         1.0      
    angularUpdate:        0.5 
    temporalUpdate:       -1.0    

    resampleThreshold:    0.5  
    particles:            30

    # Initial Map Size & Resolution
    xmin:                -2.0
    ymin:                -2.0
    xmax:                 2.0
    ymax:                 2.0
    delta:                0.05
    llsamplerange:        0.01           
    llsamplestep:         0.01
    lasamplerange:        0.005  
    lasamplestep:         0.005
    
    transform_publish_period:  0.05       
    occ_thresh:           0.25
    tf_delay:             0.1

map_saver_server:
  ros__parameters:
    use_sim_time: True
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True